import fs from 'fs';
import path from 'path';
import {MongoClient} from 'mongodb';

export function buildCommentPath(){
  return path.join(process.cwd(), 'data', 'comments.json');
}

export function extractComments(filePath){
  const fileData = fs.readFileSync(filePath);
  const data = JSON.parse(fileData);
  return data;
}

//this endpoint is hit from /pages/events/[eventId] -> components/input/comments -> to this current page (pages/api/events/index.js)
async function handler(req, res) {
  const eventId = req.query.eventId;  //pages/api/comments/[eventId]

  //connect to mongodb
  const client = await MongoClient.connect(`mongodb+srv://${process.env.MONGO_USERNAME}:${process.env.MONGO_PASSWORD}@cluster0.zj9aoqq.mongodb.net/${process.env.MONGO_DBNAME}?retryWrites=true&w=majority&appName=Cluster0`);

  if(req.method === 'POST'){

    /*
    //structure of new comment (components/input/comments )

    const newComment = {
      email,
      name, 
      text
    };
    */
    const {email, name, text } = req.body; 

    //do server-side validation
    if(!email.includes('@') || !name || !text || name.trim() === '' || text.trim() === ''){
      res.status(422).json({
        message: 'invalid input'
      })
      return;
    }
    //-------------------------
    console.log(email, name, text);

    const newComment = {
      name, 
      email, 
      text,
      eventId
    };

    
    
    //read data/comments.json
    // const filePath = buildCommentPath();
    // const data = extractComments(filePath);
    // data.push(newComment);//add new data
    //store in file data/comments.json write with 'blocking' (synchronously)
    // fs.writeFileSync(filePath, JSON.stringify(data));
  
    //write to db
    const db = client.db();
    const result = await db.collection('comments').insertOne(newComment); //collection is like a db table
    console.log(result);
    newComment.id = result.insertedId;

    res.status(201).json({message: 'success', comment: newComment});
  }

  //return all coments
  if(req.method === 'GET'){

    //localStorage
    // const dummyList = [
    //   {id:'c1', name:"max", text:"bla bla"},
    //   {id:'c2', name:"manuel", text:"ble ble"},
    // ];
    // const filePath = buildCommentPath();
    // const data = extractComments(filePath);

    //mongodb
    const db = client.db();
    const documents = await db.collection('comments').find().sort({_id:-1}).toArray();  //_id:-1 sorts by id (descending), _id is autogenerated by mongodb
    res.status(200).json({comments: documents});
  }

  client.close();

}

export default handler;
